hibernate:
  session:
    packageScan: com.quick.demo.entity
    properties:
      hibernate-hbm2dd-auto: update
      hibernate-show_sql: true
      hibernate-format_sql: true
      hibernate-dialect: org.hibernate.dialect.H2Dialect
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

